# prefix is where the environment will be created
# in the below case it will be created in a folder called env in CWD
# conda env create --prefix ./env --file environment.yml --prune

name: IntpDataStatsPy

dependencies:
  - python=3.7
  - jupyter==1.0.0
  - pandas==1.1.2
  - numpy
  - scipy==1.5.2
  - matplotlib==3.3.1
  - seaborn==0.11.0
  - scikit-learn
  - statsmodels==0.12.0
  - pip
  - pip:
    - .